project:
  type: website
  output-dir: docs

website:
  title: "Sergei Istomin's place"
  navbar:
    right:
      - about.qmd
      - icon: telegram
        href: https://t.me/sergey_istomin
      - icon: linkedin
        href: https://www.linkedin.com/in/sergeyistomin/
      - icon: envelope-fill
        href: mailto:sergey.istomin@gmail.com
format:
  html:
    theme: superhero
    css: styles.css
