---
title: "Short CV in russian"
about:
  template: marquee
  links:
    - icon: telegram
      text: Telegram
      href: https://t.me/sergey_istomin
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/sergeyistomin/
    - icon: envelope-fill
      text: Email
      href: mailto:sergey.istomin@gmail.com
---



# Сергей Истомин

Старший Python-разработчик / Технический руководитель  
Местоположение: Санкт-Петербург, Россия  

**Контакты:**  
● Телефон: +7 (911) 9125372  
● Email: sergey.istomin@gmail.com *(предпочтительно)*  
● Telegram: istomin_sergey  

**Доступность:**  
● Не готов к переезду  
● Готов к редким командировкам  
● Желаемая должность: Старший Python-разработчик / Инженер по машинному обучению  

## О себе

Опытный старший Python-разработчик и технический руководитель с более чем 10-летним стажем в разработке программного обеспечения, системной интеграции и IT-консалтинге. Владею Python, Django и различными облачными технологиями, включая AWS и Azure. Имею подтвержденный опыт управления командами, внедрения Agile-практик и реализации высококачественных решений.

## Навыки

- Python; PostgreSQL; Git; Linux; Docker; Redis; RabbitMQ; Django; HTML; Flask; Unit Testing; GitLab; Jira; MongoDB; REST; Kafka; Elasticsearch; AWS Services; Azure services.  
- Языки: Английский (Upper Intermediate), Русский (родной)  

## Образование

- Санкт-Петербургский государственный университет аэрокосмического приборостроения, Санкт-Петербург, Россия  
  Степень: Магистр компьютерных наук и управления в технических системах, 2016  
- Санкт-Петербургский политехнический университет Петра Великого  
  Степень: Бакалавр компьютерных наук и управления в технических системах, 2002  

## Опыт работы

### Профессиональный опыт

#### Tochka

- **Веб-сайт:** www.tochka.com  
- **Отрасль:**  
  - Разработка программного обеспечения  
  - Банковская сфера  
- **Должность:** Старший Python-разработчик / Инженер по машинному обучению  
- **Период работы:** Март 2024 – настоящее время (1 год 3 месяца)  
- **Ключевые достижения:**  
  - Разработал чат-бот на основе LLM-модели с использованием архитектуры Retrieval-Augmented Generation (RAG).  
    *Технологии*: Python, LangChain, LlamaIndex, Transformers, PgVector  
  - Построил CI/CD-пайплайн для автоматизации процессов развертывания и интеграции чат-бота.  
    *Технологии*: GitLab CI/CD, Docker, Kubernetes  
  - Создал бэкенд-сервисы для поддержки функциональности и производительности чат-бота.  
    *Технологии*: FastAPI, PostgreSQL, Redis  
  - Разработал и реализовал фреймворк для оценки скорости инференса LLM-моделей.  
    *Технологии*: PyTorch, Transformers, кастомные инструменты бенчмаркинга  

#### Positive Technologies Inc

- **Веб-сайт:** www.ptsecurity.ru  
- **Отрасль:**  
  - Разработка программного обеспечения, IT-безопасность  
  - Системная интеграция, IT-консалтинг  
- **Должность:** Старший Python-разработчик  
- **Период работы:** Февраль 2023 – настоящее время (1 год 2 месяца)  
- **Ключевые достижения:**  
  - Участвовал в разработке сервиса обнаружения сетевых атак (NAD) с использованием технологий Django, Celery, Postgres, ElasticSearch и Clickhouse.  
  - Реализовал эффективные механизмы логирования и передачи метрик с использованием Carbon/Graphite/Grafana.  
  - Провел рефакторинг системы аутентификации и авторизации на основе OAuth, что улучшило протоколы безопасности.  
  - Участвовал в адаптации и доработке плагинов для обнаружения атак.  

#### Quantum Soft LLC

- **Веб-сайт:** www.quantumsoft.pro  
- **Отрасль:** IT, системная интеграция, интернет  
- **Должность:** Старший Python-разработчик  
- **Период работы:** Июль 2021 – Сентябрь 2022 (1 год 3 месяца)  
- **Ключевые обязанности и достижения:**  
  - Внес значительный вклад в проект для Korn Ferry, разрабатывая систему рекомендаций на основе ML.  
  - Разработал сервисы для доступа к ML на платформе MS Azure, используя технологии Azure VM, Azure Functions, Service Bus, Eventgrid, Terraform, Python-asynclo, fastapi и pydantic.  

#### EPAM Systems Inc

- **Веб-сайт:** www.epam-group.ru  
- **Отрасль:** IT, системная интеграция, интернет  
  - Системная интеграция, автоматизация технологических и бизнес-процессов, IT-консалтинг  
- **Должность:** Старший Python-разработчик  
- **Период работы:** Апрель 2019 – Июль 2021 (2 года 4 месяца)  
- **Ключевые достижения:**  
  - Участвовал в нескольких проектах с использованием передовых технологий:  
    - Участвовал в проекте на базе AWS для Audigent Inc., включающем ML-модели и scrapy для расчета тем страниц.  
    - Разработал проект сбора данных с использованием AWS Lambda, Python и Go, оптимизировав скрипты для подготовки данных для ML для Merk Inc. (Python и Docker).  
    - Участвовал в создании среды нагрузочного тестирования для европейского поставщика контента с использованием Docker stack, Python + asynclo, Nomad от HashiCorp и RabbitMQ.  

#### Bars Group Inc

- **Веб-сайт:** bars.group  
- **Отрасль:** IT, системная интеграция, интернет  
  - Разработка программного обеспечения  
  - Системная интеграция, автоматизация технологических и бизнес-процессов, IT-консалтинг  
- **Должность:** Старший Python-разработчик / Руководитель команды  
- **Период работы:** Январь 2016 – Март 2019 (3 года 3 месяца)  
- **Ключевые обязанности:**  
  - Руководил проектами по облачному учету и кадровому учету для бюджетных организаций, обеспечивая их внедрение в нескольких регионах.  
  - Управлял распределенной командой в Санкт-Петербурге, Новосибирске и Хабаровске, внедряя Agile-практики и контролируя процесс разработки.  

## Дополнительная информация

- Разработчик с более чем 10-летним опытом работы с различными технологическими стеками, специализация — Python.  
- Опыт разработки приложений для облачных платформ AWS и Azure с акцентом на масштабируемость и высокую производительность.  